name: Setup
description: Setup Bun

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
    - run: bun install --frozen-lockfile
      shell: bash
