name: Bun Diff

on:
  pull_request:

jobs:
  bun-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: koki-develop/bun-diff-action@v1
