name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        description: The level of the bump.
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: koki-develop/bump-semver-action@b9704523ee432bbde31ee70e8ffb8a41947b3c42 # v1.1.0
        id: bump
        with:
          level: ${{ inputs.level }}

      - uses: koki-develop/major-version-sync@b86eb31aef1c06d81f133799b35ace3c80ebdf0a # v1.2.0
        with:
          version: ${{ steps.bump.outputs.new-version }}

      - name: Create release
        env:
          CURRENT_VERSION: ${{ steps.bump.outputs.current-version }}
          NEW_VERSION: ${{ steps.bump.outputs.new-version }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${NEW_VERSION}" \
            --repo "${GITHUB_REPOSITORY}" \
            --title "${NEW_VERSION}" \
            --generate-notes \
            --notes-start-tag "${CURRENT_VERSION}"
